before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: varnish-towncrier
    ldflags:
      - -s -w -X github.com/emgag/varnish-towncrier/internal/lib/version.Version={{.Version}} -X github.com/emgag/varnish-towncrier/internal/lib/version.Commit={{.Commit}} -X github.com/emgag/varnish-towncrier/internal/lib/version.Date={{.Date}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - files:
      - LICENSE
      - README.md
      - varnish-towncrier.yml.dist
checksum:
  name_template: 'checksums.txt'
dockers:
  - goos: linux
    goarch: amd64
    ids:
      - varnish-towncrier
    image_templates:
      - "emgag/varnish-towncrier:latest"
      - "emgag/varnish-towncrier:{{ .Tag }}"
      - "ghcr.io/emgag/varnish-towncrier:latest"
      - "ghcr.io/emgag/varnish-towncrier:{{ .Tag }}"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
